import type { ReactNode } from "react";

import { IBM_Plex_Sans, Gloock, Germania_One } from "next/font/google";

import "@/styles/globals.css";

import { Header, Footer, Theme, Main } from "@/components";

import GlobalData from "../content/global/index.json";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const serif = Gloock({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--serif",
});

const sans = IBM_Plex_Sans({
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--sans",
});

const display = Germania_One({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--display",
});

export default function RootLayout({ children }: { children: ReactNode }) {
  const { footer, header } = GlobalData;
  const cnBody = `min-h-screen flex flex-col ${serif.variable} ${sans.variable} ${display.variable}`;
  return (
    <html lang="en" data-theme="light">
      <body className={cnBody}>
        <Theme>
          <Header {...header} />
          <Main>{children}</Main>
          <Footer {...footer} />
        </Theme>
      </body>
    </html>
  );
}
